---
- hosts: all
  vars:
    root_db_password: 123
  gather_facts: True
  handlers:
    - name: Restart mysql
      service: name=mysql state=restarted
  tasks:
    - name: Install MySQL packages
      apt: state=installed pkg={{ item }} update_cache=yes
      with_items:
        - python-mysqldb
        - mysql-server

    - name: Start the MySQL service
      service: name=mysql state=started

    - name: Change root user password on first run
      mysql_user: name=root
                  password={{ root_db_password }}
                  priv=*.*:ALL,GRANT
                  host={{ item }}
      with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost
        - '%'

    - name: Copy the my.cnf
      copy: src=my.cnf dest=/root/.my.cnf owner=root mode=0600

    - name: delete anonymous MySQL server user for {{ ansible_hostname }}
      action: mysql_user user="" host="{{ ansible_hostname }}" state="absent"
     
    - name: delete anonymous MySQL server user for localhost
      action: mysql_user user="" state="absent"
     
    - name: remove the MySQL test database
      action: mysql_db db=test state=absent

    - name: Set mysql bind address
      lineinfile: dest=/etc/mysql/my.cnf regexp='^bind-address' line="bind-address = {{ (ansible_eth1|default(ansible_eth0)).ipv4.address }}"
      notify: Restart mysql
